#!/bin/sh
### BEGIN INIT INFO
# Provides:          klipper
# Required-Start:    $local_fs $remote_fs $network klipper-firmware-dsp klipper-firmware-toolhead klipper-firmware-bed
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Klipper 3D Printer Firmware
### END INIT INFO

KLIPPY_EXEC="/usr/bin/python3"
KLIPPY_ARGS="-O /usr/share/klipper/klippy/klippy.py /etc/klipper/config/printer.cfg -l /board-resource/klippy.log -a /run/klippy.sock"
PIDFILE="/var/run/klipper.pid"

case "$1" in
    start)
        echo "Starting klipper..."
        start-stop-daemon -S -b -m -p $PIDFILE \
            -x $KLIPPY_EXEC -- $KLIPPY_ARGS
        ;;
    stop)
        echo "Stopping klipper..."
        start-stop-daemon -K -p $PIDFILE -R 10
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
            echo "klipper is running (PID $(cat $PIDFILE))"
        else
            echo "klipper is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
