#!/bin/sh
### BEGIN INIT INFO
# Provides:          ustreamer
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: uStreamer MJPEG-HTTP streamer
### END INIT INFO

USTREAMER_EXEC="/usr/bin/ustreamer-wrapper"
USTREAMER_ARGS="-r 864x480 -c HW -m MJPEG -b 1 -w 1 -f 10 -l --host=0.0.0.0 --allow-origin=*"
PIDFILE="/var/run/ustreamer.pid"

case "$1" in
    start)
        echo "Starting ustreamer..."
        start-stop-daemon -S -b -m -p $PIDFILE \
            -x $USTREAMER_EXEC -- $USTREAMER_ARGS
        ;;
    stop)
        echo "Stopping ustreamer..."
        start-stop-daemon -K -p $PIDFILE -R 10
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
            echo "ustreamer is running (PID $(cat $PIDFILE))"
        else
            echo "ustreamer is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
