#@TYPE: Machine
#@NAME: Elegoo Centauri Carbon 1
#@DESCRIPTION: Machine configuration for the Elegoo Centauri Carbon 1, based on the Allwinner R528 CPU

require conf/machine/include/sun8i.inc

#KERNEL_DEVICETREE = "allwinner/elegoo-centauri-carbon1.dtb"
KERNEL_DEVICETREE = "allwinner/sun8i-t113s-mangopi-mq-r-t113.dtb"
KERNEL_IMAGETYPE = "zImage"
#KERNEL_IMAGETYPE = "uImage"
#KERNEL_DEVICETREE_BUNDLE = "1"
UBOOT_ENTRYPOINT = "0x43000000"
SERIAL_CONSOLES = "115200;ttyS0"

UBOOT_MACHINE = "elegoo_centauri_carbon1_defconfig"
