#!/bin/sh
### BEGIN INIT INFO
# Provides:          moonraker
# Required-Start:    $local_fs $remote_fs $network klipper
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Moonraker API Server for Klipper
### END INIT INFO

MOONRAKER_EXEC="/usr/bin/python3"
MOONRAKER_ARGS="-m moonraker.moonraker -d /etc/klipper -l /board-resource/moonraker.log -u /run/moonraker.sock"
PIDFILE="/var/run/moonraker.pid"

export PYTHONPATH="/usr/share/moonraker"
export PATH="/usr/share/moonraker:/usr/sbin:/usr/bin:/sbin:/bin"
export TMPDIR="/user-resource/.tmp"

case "$1" in
    start)
        echo "Starting moonraker..."
        # Clean up OpenCentauri so moonraker doesn't index everything here
        rm -rf /user-resource/OpenCentauri
        mkdir -p /user-resource/.tmp
        mkdir -p /user-resource/gcodes

        if [ -d /etc/webui ]; then
            rm -f /etc/webui
        fi

        ln -sf "/var/www/$(config-manager ui web_ui)/" /etc/webui

        start-stop-daemon -S -b -m -p $PIDFILE \
            -x $MOONRAKER_EXEC -- $MOONRAKER_ARGS
        ;;
    stop)
        echo "Stopping moonraker..."
        start-stop-daemon -K -p $PIDFILE -R 10
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
            echo "moonraker is running (PID $(cat $PIDFILE))"
        else
            echo "moonraker is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
