#!/bin/sh

if [ ! -f "$1" ]; then
    echo "Usage: $0 path/to/update.swu"
    exit 1
fi

curr=$(fw_printenv systemAB_next | awk -F= '{ print $2 }' | tr -d '[:space:]')

if [[ "$curr" == "A" ]]; then
    boot_partition="now_A_next_B"
elif [[ "$curr" == "B" ]]; then
    boot_partition="now_B_next_A"
else
    exit 1
fi

echo "$boot_partition"

set -e

swupdate -v -i "$1" -e stable,${boot_partition}
sync
echo "Update finished, run 'reboot' to finalize"
