require conf/distro/poky.conf

DISTRO = "cosmos"
DISTRO_NAME = "OpenCentauri Cosmos"
DISTRO_VERSION = "0.0.4"

MAINTAINER = "James Turton <james.turton@gmx.com>"

PACKAGE_CLASSES = "package_ipk"
DISTRO_FEATURES:remove = "ptest"

DISTRO_FEATURES:append = " rust"
RUST_VERSION = "1.92.0"
CARGO_VERSION = "1.92.0"
