#!/bin/sh
### BEGIN INIT INFO
# Provides:          mjpg-streamer
# Required-Start:    $local_fs $remote_fs $network opencentauri-firmware
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Klipper 3D Printer Firmware
### END INIT INFO

MJPEG_EXEC="/usr/bin/mjpg_streamer"
MJPEG_INPUT_ARGS="input_uvc.so -d /dev/video0 -r 1280x720 -f 30"
MJPEG_OUTPUT_ARGS="output_http.so -p 8080"
MJPEG_EXTRA_ARGS=""
PIDFILE="/var/run/mjpg-streamer.pid"

case "$1" in
    start)
        echo "Starting mjpg-streamer..."
        start-stop-daemon -S -b -m -p $PIDFILE \
            -x $MJPEG_EXEC -- -i "$MJPEG_INPUT_ARGS" -o "$MJPEG_OUTPUT_ARGS" \
            $MJPEG_EXTRA_ARGS

        echo 1000 > /proc/$(cat $PIDFILE)/oom_score_adj
        ;;
    stop)
        echo "Stopping mjpg-streamer..."
        start-stop-daemon -K -p $PIDFILE -R 10
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
            echo "mjpg-streamer is running (PID $(cat $PIDFILE))"
        else
            echo "mjpg-streamer is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
