name: Build OpenCentauri Image

on:
  workflow_call:
    inputs:
      use_cache:
        type: boolean
        default: true
      write_back_cache:
        type: boolean
        default: false
      upload_all_artifacts:
        type: boolean
        default: false
      version:
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use cache'
        type: boolean
        default: true
      write_back_cache:
        description: 'Write back cache'
        type: boolean
        default: false
      upload_all_artifacts:
        description: 'Upload all artifacts'
        type: boolean
        default: false
      version:
        description: 'Override distro version'
        type: string
        default: ''

env:
  # Sims server cache dir
  CACHE_DIR: /data/cache

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Restore cache
        if: ${{ inputs.use_cache }}
        run: |
          mkdir -p ./build
          cp -ar ${{ env.CACHE_DIR }}/* ./build

      - name: Set distro version
        if: ${{ inputs.version != '' }}
        run: |
          version="${{ inputs.version }}"
          version="${version:0:10}"
          sed -i -E "s/^DISTRO_VERSION = \".*\"/DISTRO_VERSION = \"${version}\"/" meta-opencentauri/conf/distro/cosmos.conf

      - name: Build image
        run: |
          source poky/oe-init-build-env build
          bitbake opencentauri-upgrade

      - name: Upload build artifacts (SWU only)
        uses: actions/upload-artifact@v4
        with:
          name: CC1 Firmware
          path: build/tmp/deploy/images/elegoo-centauri-carbon1/opencentauri-upgrade-elegoo-centauri-carbon1.rootfs.swu

      - name: Upload build artifacts
        if: ${{ inputs.upload_all_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: elegoo-centauri-carbon1-images
          path: build/tmp/deploy/images/elegoo-centauri-carbon1/

      - name: Write back cache
        if: ${{ inputs.write_back_cache }}
        run: |
          rm -rf ${{ env.CACHE_DIR }}/*
          cp -ar ./build/downloads ${{ env.CACHE_DIR }}
          cp -ar ./build/sstate-cache ${{ env.CACHE_DIR }}

      - name: Clean workspace
        if: always()
        run: git clean -ffdx
