name: Build OpenCentauri Image (on PR)
on:
  pull_request:

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: approval-needed
    steps:
      - run: echo "Approved"

  build:
    needs: approve
    uses: ./.github/workflows/build.yml
    with:
      use_cache: true
      write_back_cache: false
      upload_all_artifacts: false